# Generated by Django 6.0.8 on 2026-08-05 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_CARD', 'Buletin (Verificare Vârstă)'), ('VET_LICENSE', 'Atestat Medic Veterinar')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('APPROVED', 'Aprobat'), ('REJECTED', 'Respins')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Completat doar dacă este respins', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
